#ansible-playbook -i localhost, -e instances=['mongodb','catalogue','redis','user','cart','mysql','shipping','rabbitmq','payment','frontend'] roboshop.yaml

- name: create ec2 and r53 records
  hosts: all
  connection: local
  vars:
   sg_id: sg-0e952a919361d18ab
   ami_id: ami-0220d79f3f480ecf5
   env: dev
   action: create
   domain_name: sivadevops.site
   instances:
    - mongodb
    - catalogue
  tasks:
   - name: create ec2 instances
     amazon.aws.ec2_instance:
      vpc_subnet_id: subnet-0e2d2a34508988aa6
      security_group: "{{sg_id}}"
      instance_type: t2.micro
      image_id: "{{ami_id}}"
      name: "{{item}}-{{env}}"
      tags:
       Project: roboshop
       Catalogue: "{{item}}"
       Environment: "{{env}}"
       Name: "{{item}}-{{env}}"
     loop: "{{instances}}"
     register: ec2_output
     when: action == "create"
     
   - name: print the output
     ansible.builtin.debug:
      msg: "{{ec2_output}}"
     when: action == "create"
     
   - name: cretae route53 record
     amazon.aws.route53:
      state: present
      ttl: 1
      type: A
      zone: "{{domain_name}}"
      record: "{{item.item}}-{{env}}.{{domain_name}}"
      value: "{{item.instances[0].private_ip_address}}"
      wait: true
     loop: "{{ec2_output.results}}"
     when: action == "create"
   
   - name: create route53 record for frontend
     amazon.aws.route53:
      state: present
      zone: "{{domain_name}}"
      type: A
      ttl: 1
      record: "roboshop-{{env}}.{{domain_name}}"
      value: "{{item.instances[0].public_ip_address}}"
      wait: true
     loop: "{{ec2_output.results}}"
     when: # and
      - item.item == "frontend"
      - action == "create"
      
   - name: delete route53 records
     amazon.aws.route53:
      state: absent
      zone: "{{domain_name}}"
      record: "{{item}}-{{env}}.{{domain_name}}"
      type: A
      ttl: 1
     loop: "{{instances}}"
     when: action == "destroy"
     
   - name: Delete ec2 instance
     amazon.aws.ec2_instance:
      state: absent
      region: us-east-1
      filters:
      "tag:Name": "{{ item }}-{{ env }}"
      # name: "{{item}}-{{env}}"
     loop:
      - mongodb
      - catalogue
     when: action == "destroy"